// <auto-generated />
using System;
using HoldsSimpleWebAppCore22.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HoldsSimpleWebAppCore22.Migrations
{
    [DbContext(typeof(HoldsSimpleWebAppCore22Context))]
    partial class HoldsSimpleWebAppCore22ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HoldsSimpleWebApp.Models.OrderHold", b =>
                {
                    b.Property<int>("OrderHoldID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("OrderDate");

                    b.Property<string>("OrderHoldCode");

                    b.Property<string>("OrderHoldDesc");

                    b.Property<int>("OrderID");

                    b.HasKey("OrderHoldID");

                    b.ToTable("OrderHold");
                });
#pragma warning restore 612, 618
        }
    }
}
